// Slice 1 domain types for Limen.
// Mirrors first-slice.md sections 3 ("Modelo de policy", "Formato de resposta",
// "AuditEvent canônico", "Operadores e gramática") and strategic-decisions §14.

export type Scalar = string | number | boolean;

// Operators allowed in slice 1. Adding more (eq, neq, gt, gte, lt, lte,
// starts_with, ends_with, matches, exists) is mechanical: extend this type and
// register the function in the evaluator dispatch.
export type Predicate = {
  in?: readonly Scalar[];
  not_in?: readonly Scalar[];
  contains?: string;
};

// AND across field keys (every key in `deny_when` must match for the Rule to
// fire). AND across multiple predicates on the same field, when present.
// OR across Rules is handled by the evaluator and is not encoded in the type.
export type WhenClause = Record<string, Predicate>;

// Every Rule under `rules:` is implicitly deny; the condition lives under
// `deny_when:` so the verb sits next to the condition it qualifies (ADR 0001).
// `allow_when:` (positive sugar) is reserved for slice 3+ and will desugar
// to `deny_when not X` at load time, leaving the engine deny-only forever.
export type Rule = {
  id: string;
  description?: string;
  deny_when: WhenClause;
};

// Stored at policies/<tool>.yaml. The Tool name is implicit from the filename;
// there is no `tool:` field in the body (ADR 0002).
export type Policy = {
  version: 1;
  rules: Rule[];
};

// Verdict produced by the Policy engine. `pending_approval` is reserved for
// slice 2+; `error` covers a quarantined Tool (e.g., invalid YAML at boot).
export type Decision = 'allow' | 'deny' | 'pending_approval' | 'error';

// One specific reason a Rule's `when` matched. Multiple violations can come
// from a single Rule (e.g., several recipients failing the same allowlist).
export type Violation = {
  field: string;
  value: unknown;
  message: string;
};

export type Denial = {
  ruleId: string;
  reason: string;
  violations: Violation[];
};

// Adapter failure (Gmail 5xx, network, expired refresh token, etc.).
// `retryable` is a hint to the agent, not a runtime guarantee.
export type AdapterError = {
  type: 'adapter_error';
  code: string;
  retryable: boolean;
  detail?: string;
};

// Engine failure that prevents a Decision (Tool quarantined: invalid policy YAML, etc.).
export type EngineError = {
  type: 'engine_error';
  code: string;
  detail: string;
};

// Outcome of running an Adapter when the Decision is `allow`. The Adapter
// contract returns this directly (ADR 0005); the AuditEvent.execution field
// records the same value. `status` mirrors `executed`: success ↔ executed=true,
// failed ↔ executed=false.
export type AdapterResult =
  | { status: 'success'; result: Record<string, unknown> }
  | { status: 'failed'; error: AdapterError };

// Per-call shape invariants the discriminated union enforces (cf. the Decision
// table in first-slice.md):
//   allow            → execution non-null;     denials null;            error null
//   deny             → execution null;         denials non-null array;  error null
//   pending_approval → execution, denials, error all null
//   error            → execution null;         denials null;            error non-null
//
// `executed` is true only when decision='allow' AND execution.status='success'.
// One AuditEvent per Tool call, emitted once at the end via console.log(JSON.stringify(event)).
type AuditEventBase = {
  schemaVersion: 1;
  // ULID generated by Limen, distinct from request.jsonRpcId (which is the agent's).
  eventId: string;
  // ISO 8601 with milliseconds.
  timestamp: string;
  tool: string;
  request: {
    jsonRpcId: number | string | null;
    // Raw and complete; PII redaction is future work (see feature-ideas.md).
    params: Record<string, unknown>;
  };
  durationMs: number;
};

export type AuditEvent = AuditEventBase &
  (
    | {
        decision: 'allow';
        executed: boolean;
        execution: AdapterResult;
        denials: null;
        error: null;
      }
    | {
        decision: 'deny';
        executed: false;
        denials: Denial[];
        execution: null;
        error: null;
      }
    | {
        decision: 'pending_approval';
        executed: false;
        denials: null;
        execution: null;
        error: null;
      }
    | {
        decision: 'error';
        executed: false;
        denials: null;
        execution: null;
        error: EngineError;
      }
  );

// What the handler provides to the audit logger. The system-generated fields
// (schemaVersion, eventId, timestamp) are added by recordAuditEvent().
export type AuditEventInput = Omit<AuditEvent, 'schemaVersion' | 'eventId' | 'timestamp'>;
